version: '3.7'
services:
  database:
    image: mysql:5.7
    container_name: bookstore_db
    environment:
      MYSQL_ROOT_PASSWORD: R1234
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: yavuz_69
      MYSQL_PASSWORD: yavuz6969
    networks:
      - book-net  
  myapp:
    image: yavuz69/bookstoreapi:latest
    restart: always
    container_name: bookstore_app
    depends_on: 
      - database
    ports:
      - "80:80"   
    networks:
      - book-net
networks: 
  book-net: 
    driver: bridge
